# Create environment:
# conda env create -f environment.yml
#
# Update environment when there is an change:
# conda env update -f environment.yml --prune
#
# Remove environment:
# conda remove --name dl4h-project --all
#
# Frequently used command:
# conda env list
# conda activate [env name: dl4h-project]
# pip list
#
name: dl4h-project
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.7
  - Cython
  - pip:
      - --requirement requirements.txt